# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prof_name', models.CharField(max_length=100)),
                ('Prof_dept', models.CharField(max_length=100)),
                ('Prof_position', models.CharField(max_length=1000)),
                ('Prof_image', models.ImageField(upload_to='')),
                ('Prof_address', models.CharField(max_length=1000)),
                ('Prof_phoneo', models.IntegerField(max_length=1000)),
                ('Prof_phoner', models.IntegerField(max_length=1000)),
                ('Prof_email', models.EmailField(max_length=1000)),
                ('Prof_room', models.CharField(max_length=1000)),
                ('Prof_ri', models.CharField(max_length=1000)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Dept')),
            ],
        ),
    ]
