# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171111_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='prof',
            name='dept',
        ),
        migrations.AlterField(
            model_name='prof',
            name='Prof_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Dept'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='Prof_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Position'),
        ),
    ]
