# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171111_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Project_Funding_agency', models.CharField(max_length=100)),
                ('Project_detail', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publication_name', models.CharField(max_length=100)),
                ('Publication_detail', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recognition_name', models.CharField(max_length=100)),
                ('Recognition_detail', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Student_detail', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teaching_name', models.CharField(max_length=100)),
                ('Teaching_detail', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_detail1',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_detail2',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_detail3',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prof',
            name='Prof_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='teaching',
            name='Teaching_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prof'),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prof'),
        ),
        migrations.AddField(
            model_name='recognition',
            name='Recognition_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prof'),
        ),
        migrations.AddField(
            model_name='publication',
            name='Publication_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prof'),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prof'),
        ),
    ]
