# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20171114_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='Dept_detail3',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='Dept_image2',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='Dept_image3',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='Prof_address',
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_Fax',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_address1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_address2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='Dept_phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='Prof_address1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='Prof_address2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
