# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20171114_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_name', models.CharField(max_length=100)),
                ('Facility_description', models.TextField(max_length=10000)),
                ('Facility_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Dept')),
            ],
        ),
    ]
