# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_dept_dept_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 14, 25, 45, 570144)),
        ),
    ]
