# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 15, 47, 36, 117570)),
        ),
    ]
