# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20171114_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Dept_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 21, 13, 33, 935251)),
        ),
    ]
