# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_auto_20171114_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 302033)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 302013)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 299596)),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 300001)),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 300471)),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 300442)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 301594)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 47, 1, 301574)),
        ),
    ]
