# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20171116_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expreience',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 577410)),
        ),
        migrations.AlterField(
            model_name='expreience',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 577388)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 576975)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 576956)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 574581)),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='Date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 574988)),
        ),
        migrations.AlterField(
            model_name='student',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 575400)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 575379)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 576535)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 19, 22, 37, 576515)),
        ),
    ]
