# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20171118_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expreience',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 741645)),
        ),
        migrations.AlterField(
            model_name='expreience',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 741620)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 741137)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 741112)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 738402)),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='Date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 738830)),
        ),
        migrations.AlterField(
            model_name='student',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 739259)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 739240)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 740661)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 23, 13, 12, 740640)),
        ),
    ]
