# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20171119_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Detail', models.CharField(max_length=10000)),
                ('Start_date', models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 523335))),
                ('End_date', models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 523356))),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Prof')),
            ],
        ),
        migrations.RemoveField(
            model_name='expreience',
            name='Professor',
        ),
        migrations.AlterField(
            model_name='dept',
            name='Dept_Fax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='Dept_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 522929)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 522910)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 520550)),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='Date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 520955)),
        ),
        migrations.AlterField(
            model_name='student',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 521364)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 521344)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='End_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 522484)),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='Start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 17, 59, 12, 522465)),
        ),
        migrations.DeleteModel(
            name='Expreience',
        ),
    ]
